### ISSUE TITLE
`ModuleNotFoundError: No module named 'docx'` `'exceptions'` `'bs4'` (Solved)

### ISSUE THREAD

**Issue by cczallen** [iamch15542/ImageDownloader#1]
在 macOS Catalina 10.15.7
直接運行會依序發生以下錯誤：
`ModuleNotFoundError: No module named 'docx'`
`ModuleNotFoundError: No module named 'exceptions'`
`ModuleNotFoundError: No module named 'bs4'`

經過 Google 後，依序安裝：
`pip3 install docx`
`pip3 install python-docx`
`pip3 install beautifulsoup4`
可以解決，成功運行。

**Comment by iamch15542** [comment]
這是我的問題，因為只是小程式，所以就沒寫得那麼完善XDD
再 README 補上了，也謝謝你開issue~
